[package]
name = "firmware-manager-notify"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[features]
system76 = []
fwupd = []

[build-dependencies]
markup = "0.3.1"

[dependencies]
firmware-manager = { path = "../" }
err-derive = "0.1.5"
notify-rust = "3.6.0"
reqwest = "0.9.19"

[target.'cfg(all(not(feature = "fwupd"), feature = "system76"))'.dependencies]
firmware-manager = { path = "../", features = [ "system76" ] }

[target.'cfg(all(feature = "fwupd", not(feature = "system76")))'.dependencies]
firmware-manager = { path = "../", features = [ "fwupd" ] }

[target.'cfg(all(feature = "fwupd", feature = "system76"))'.dependencies]
firmware-manager = { path = "../", features = [ "fwupd", "system76" ] }
