[package]
name = "firmware-manager"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[workspace]
members = [ "gtk", "gtk/ffi", "notify", "tools" ]

[features]
default = [ "fwupd", "system76" ]
fwupd = [ "fwupd-dbus" ]
system76 = [ "system76-firmware-daemon" ]

[build-dependencies]
markup = "0.3"

[dependencies]
err-derive = "0.1.5"
fwupd-dbus = { git = "https://github.com/pop-os/fwupd-dbus", optional = true }
system76-firmware-daemon = { git = "https://github.com/pop-os/system76-firmware", optional = true }
slotmap = "0.3.0"
shrinkwraprs = "0.2.1"
reqwest = "0.9.19"
human-sort = "0.2.2"
xdg = "2.2.0"
better-panic = "0.1.2"
