[package]
name = "firmware-manager"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[workspace]
members = [ "gtk", "gtk/ffi", "notify", "tools" ]

[features]
fwupd = [ "fwupd-dbus" ]
system76 = [ "system76-firmware-daemon" ]

[dependencies]
err-derive = "0.1.5"
fwupd-dbus = { git = "https://github.com/pop-os/fwupd-dbus", optional = true }
system76-firmware-daemon = { git = "https://github.com/pop-os/system76-firmware", branch = "firmware-client", optional = true }
slotmap = "0.3.0"
shrinkwraprs = "0.2.1"
reqwest = "0.9.18"
