[package]
name = "firmware-manager"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[workspace]
members = [ "ffi" ]

[dependencies]
gtk = {version = "0.6.0", features = [ "v3_24" ] }
cascade = "0.1.3"
gio = "0.6.0"
glib = "0.7.1"
system76-firmware-daemon = { git = "https://github.com/pop-os/system76-firmware", branch = "firmware-client" }
err-derive = "0.1.5"
shrinkwraprs = "0.2.1"
