[package]
name = "firmware-manager-gtk"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[features]
fwupd = []
system76 = []

[dependencies]
cascade = "0.1"
err-derive = "0.1"
gio = "0.7"
glib = "0.8"
gtk = {version = "0.7", features = [ "v3_22" ] }
shrinkwraprs = "0.2"
slotmap = "0.3"
html2runes = "1.0"
firmware-manager = { path = "../" }

[target.'cfg(all(not(feature = "fwupd"), feature = "system76"))'.dependencies]
firmware-manager = { path = "../", features = [ "system76" ] }

[target.'cfg(all(feature = "fwupd", not(feature = "system76")))'.dependencies]
firmware-manager = { path = "../", features = [ "fwupd" ] }

[target.'cfg(all(feature = "fwupd", feature = "system76"))'.dependencies]
firmware-manager = { path = "../", features = [ "fwupd", "system76" ] }